### ISSUE TITLE
[JOSS-review] add DOI to references in paper-bib, where possible

### ISSUE THREAD

**Issue by strengejacke** [andrewthomasjones/logKDE#1]
This one is related to https://github.com/openjournals/joss-reviews/issues/870.

Please add DOI's to the references in the paper, if references have a DOI.

**Comment by hiendn** [comment]
Hi @strengejacke,

All DOIs that could be found have now been added to the paper. Please see the latest generated PDF document over at [https://github.com/openjournals/joss-reviews/issues/870](https://github.com/openjournals/joss-reviews/issues/870).

Please let me know if you are happy with this.

**Comment by strengejacke** [comment]
Thanks, looks fine!
