### ISSUE TITLE
[JOSS-review] References in docs

### ISSUE THREAD

**Issue by strengejacke** [andrewthomasjones/logKDE#3]
This is not a strict prerequisite, but you may consider adding a references to your documentation inside the R-package (help-files), e.g. `?logdensity`. I guess you may copy a reference from your vignette-paper.

**Comment by hiendn** [comment]
Hi @strengejacke ,

References have now been added to the main functions (i.e. the only new functions that we have added). Please reinstall the package from the GitHub repository using

`devtools::install_github('andrewthomasjones/logKDE',build_vignettes = T)`

and let me know if you are happy with the outputs of

```
?logdensity
?logdensity_fft
?bw.logCV
?bw.logG
```

Thanks!

**Comment by strengejacke** [comment]
Yes, looks fine to me!
