### ISSUE TITLE
Probability Density Function

### ISSUE THREAD

**Issue by wanghe0127** [andrewthomasjones/logKDE#4]
Can I get the Probability Density Function of  a  distribution? Now I can only plot the figure.Thanks

**Comment by andrewthomasjones** [comment]
As can be seen in the examples and the documentation for the base density class, if we have `dens <- logdensity(values)`, then the values for the estimated pdf are `dens$y` and the values in the sample space at which they were estimated are `dens$x`.

Thanks,

Andrew
